# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ZoneLabel
                                 A QGIS plugin
 This plugin allows to manually label rectangular areas ...
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-08
        copyright            : (C) 2022 by Andrea Folini
        email                : andrea.folini@polimi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ZoneLabel class from file ZoneLabel.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .zone_label import ZoneLabel
    return ZoneLabel(iface)
